### ISSUE TITLE
Reduzir o tamanho da imagem docker gerada no processo de build

### ISSUE THREAD

**Issue by marcosnasp** [marcosnasp/temperatura-converter-service#8]
Analisar:

❯ jdeps target/temperatura-converter-service-0.0.1.jar
Exception in thread "main" java.lang.module.FindException: Module spring.boot not found, required by com.example.temperatura.converter
        at java.base/java.lang.module.Resolver.findFail(Resolver.java:892)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:420)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:254)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:604)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:558)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:534)
        at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:50)

**Comment by marcosnasp** [comment]
Imagem Reduzida para 131MB:

| REPOSITORY                   | TAG   | IMAGE ID     | CREATED      | SIZE  |
|------------------------------|-------|--------------|--------------|-------|
| temperatura-converter-server | 0.0.1 | f2317ae99bea | 17 hours ago | 131MB

```dockerfile
# Custom Java runtime using jlink in a multi-stage container build
FROM eclipse-temurin:20-jdk-jammy as jre-build

# Create a custom Java runtime
RUN $JAVA_HOME/bin/jlink \
         --add-modules jdk.unsupported,java.base,java.sql,java.naming,java.desktop,java.management,java.security.jgss,java.instrument \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /javaruntime

# Define your base image
FROM debian:stretch-slim
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=jre-build /javaruntime $JAVA_HOME

RUN mkdir /opt/app
COPY target/*.jar /opt/app/app.jar
CMD ["java", "-jar", "/opt/app/app.jar"]
```
